  select OPPID,
         LOANPRODISPLAYID,
         CLCONTRACTID,
         CDUID,
         LMS,
         PORTFOLIO,
         STAGENAME,
         STAGE,
         LEAD_SOURCE,
         APP_SOURCE,
         SEX,
         MAILING_PROVINCE,
         AGE,
         LOAN_AMOUNT,
         LOAN_INTEREST_RATE,
         ADMIN_FEE,
         INSURANCE_TERM,
         CREDIT_MONITORING,
         PAYMENT_FREQUENCY,
         FIRST_PAYEMENT_DATE,
         FUNDING_DATE,
         LOAN_CANCELLATION_DATE
from {{ source('EVERGREEN_DEMO', 'EVERGREENCUSTOMER') }}