  select LOAN_DISPLAY_ID,
         LOAN_ID,
         PORTFOLIO,
         AMOUNT,
         APPLY_DATE,
         CREATED,
         REVERSE_DATE,
         TYPE,
         REVERSED,
         PAYMENT_TYPE,
         PRINCIPAL,
         INTEREST,
         DEPOSIT,
         NSF_FEES,
         LPP,
         LPP_TAXES,
         SECURITY_CONTRIBUTION,
         BLOOM,
         BLOOM_TAXES
from {{ source('EVERGREEN_DEMO', 'PAYMENTHISTORY') }}